# Generated by Django 4.2.1 on 2023-05-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visitors_alter_faq_options_visitorstime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorstime',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_times', to='main.visitors'),
        ),
    ]
