# Generated by Django 4.2.1 on 2023-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_visitorstime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorstime',
            name='test',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
