# Generated by Django 4.2.1 on 2023-05-21 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_visitorstime_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorstime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 17, 34, 12, 167841, tzinfo=datetime.timezone.utc)),
        ),
    ]
