# Generated by Django 4.2.1 on 2023-05-21 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_visitorstime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorstime',
            name='test',
        ),
        migrations.AlterField(
            model_name='visitorstime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 17, 43, 37, 740372, tzinfo=datetime.timezone.utc)),
        ),
    ]
