# Generated by Django 4.2.1 on 2023-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_visitorstime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorstime',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
