# Generated by Django 4.2.1 on 2023-06-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contactquestions_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactquestions',
            name='time',
        ),
    ]
